### ISSUE TITLE
Move project to its own git organization

### ISSUE THREAD

**Issue by davsclaus** [camel-idea-plugin/camel-idea-plugin#267]
Hi @fharms @adrianbumbas et all. 

As this plugin started as an experiment on my git org, do you guys prefer to move this to its own git organization so it seems more neutral?

I do think it would take some time before the plugin and code is mature and ready to be donated to Apache Camel. And here at github we have more freedom and can do quicker releases etc.

**Comment by fharms** [comment]
I think that could be a good idea, but it's no rush for me.

**Comment by adrianbumbas** [comment]
I agree, no rush yet, as long as we can contribute it doesn't really matter :)

**Comment by davsclaus** [comment]
Okay if someone else feels strong about this I would leave it as-is for now. I dont have endless time to govern and move projects around.

**Comment by davsclaus** [comment]
@fharms would take a look at how much trouble it would be to move travis CI to a new org.

**Comment by davsclaus** [comment]
There is some docs here
https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

What organization name should we use?

I think this name is likely an obvious choice?
- camel-idea-plugin

**Comment by fharms** [comment]
Actually I have looked into this, just forgot to update the issue.

I don't see any problems in moving to a new git organization with travis.ci. We just have to setup a integration inside the repository settings and it should work out of the box with the current travis.yml file

+1 to camel-idea-plugin as organization

**Comment by davsclaus** [comment]
New organization has been created
https://github.com/camel-idea-plugin

**Comment by davsclaus** [comment]
Okay fingers crossed .. transferring

**Comment by davsclaus** [comment]
Okay the move is now done, and we have a new home at
https://github.com/camel-idea-plugin/camel-idea-plugin

@fharms let us know about how the travis CI move goes.

**Comment by fharms** [comment]
Travis is setup and running. Had to upgrade the Intellij version also since the 2016.3.2 is not accessible anymore.

Please run the script ./install-intellij-libs.sh for community version to download the 2017.1 and run the script install-intellij-libs.sh to update the local maven repo.

>./install-intellij-libs.sh 2017.1 /Users/JOE/Applications/IntelliJ IDEA CE.app/Contents /User/JOE/.m2

Note : the Intellij version is updated in the pom.xml file, so you will have to use 2017.1

**Comment by davsclaus** [comment]
I guess the first script is `download-unpack-intellij.sh` and not what you typed

**Comment by davsclaus** [comment]
Upgrading my IDEA to 2017.1.2 and running these scripts. I had a little trouble with the download and had to do it manually but got it to install those JARs.

**Comment by davsclaus** [comment]
Move is done
