### ISSUE TITLE
Use optional dependencies for languages plugins 

### ISSUE THREAD

**Issue by fharms** [camel-idea-plugin/camel-idea-plugin#285]
In the process of making the Camel plugin work with the code completion within endpoints split over multiple lines, I ran into an issue with our current code in the **CamelIdeaUtils** and **IdeaUtils** used to parse or scan the PSI tree for language syntax

The Camel plugin is automatic depending on the Java plugin functionality which make the API for parsing java syntax PSIElements available for us inside the Camel Plugin by default. This could be for example PsiPolyadicExpression, but for Scala, Groovy and other languages they are not using the PsiPolyadicExpression as expression to map two or more elements.

Until now we have workaround we don’t have access to other languages API’s and we typical test for name equal what we expect for the specific language. This has been fine so far but with feature like polyadic endpoint URI and testing, this will become much hard to do for other languages when we don’t have the basic functionality available for language.

I haven't investigate this in depth, but what I would suggest is that we add optional dependencies on other languages. 

>\<depends optional="true" config-file="scala-ext.xml"\>ScalaCore\</depends\>

This will of course require the various utils we have created need to be refactored to use extension point to inject into a CamelIdeaUtils and IdeaUtils depended on which language plugin the user has installed.

http://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_extensions_and_extension_points.html

We already know testing is difficult with IntelliJ SDK so we should expect this will take some time to get it to work with the various language plugins

Any thoughts on this?

**Comment by adrianbumbas** [comment]
Do you mean that the Scala plugin should handle the Camel route handling for routes defined in Scala?

**Comment by fharms** [comment]
What I mean is the language specific PSI elements isn't available to the Camel plug like we have with Java PSI elements. We only depend on Scala, Groovy etc plugins as optional

Make sense?

**Comment by adrianbumbas** [comment]
Yes.

**Comment by fharms** [comment]
I'll start working on prototype this weekend

**Comment by fharms** [comment]
@davsclaus  I have worked on using extension points to add logic so we are not depending hard on the other languages like Groovy, Scala, etc but still able to use it's APIs. I've made a simple prototype that creates an extension to IdeaUtils on extractTextFromElement method. Of course there is many ways of cutting the extension API and we might consider creating extensions on class level like IdeaUtils, CamelIdeaUtils so each language provide it's own IdeaUtils extension.

Anyway I need feedback on the prototype  https://github.com/camel-idea-plugin/camel-idea-plugin/compare/master...fharms:enable_extension_point?expand=1

**Comment by davsclaus** [comment]
Hi @fharms 

Sorry I am busy at this time. I am going to USA in about a week and have focus on that. And there is also the Camel 2.19 release which should get out the door. And my book has some deadlines now.

I updated ticket: https://github.com/camel-idea-plugin/camel-idea-plugin/issues/299

So the idea should be to get a last 0.3.x release out with a stable Camel 2.19 release.
Then afterwards we can make the master branch open for this work.

It looks fine, so you are welcome to continue with this

**Comment by davsclaus** [comment]
We can also branch on master for a 0.3.x branch so we can keep that a little bit stable in case you get far ahead with this and want to merge it into master.

**Comment by fharms** [comment]
Update: 

I have been working on getting rid of the shell/bat install script and use gradle as platform script for downloading, unpack and install IntelliJ and it's modules into maven. This is part of supporting optional dependencies and to be able to download them as part of the install and build process.

I had problem with publish local artifacts with gradle. I reach out to the gradle forum for help, but I still haven't been able to solve it with gradle.

[Install custom jars files with artifact id, group id and version into local maven repo](https://discuss.gradle.org/t/install-custom-jars-files-with-artifact-id-group-id-and-version-into-local-maven-repo/22426)

I switch strategy and decided to write a maven plugin that can download and unpack and install jars to the local maven repository instead.

**Comment by fharms** [comment]
This has chance a lot since we removed the support for Kotlin and Scala support #341 and the news is Intellij will support maven artifacts which make it much more easiere. It still make sense to use the extension API to decouple the XML and Java utilities

**Comment by fharms** [comment]
Close this one since we have deprecated support for additional languages
