### ISSUE TITLE
No camel-icon if the route uri is a constant and not a string

### ISSUE THREAD

**Issue by armagedon** [camel-idea-plugin/camel-idea-plugin#293]
![screenshot](https://cloud.githubusercontent.com/assets/5870244/23742226/5965b06a-04ac-11e7-9642-e37fd6226dd6.png)

**Comment by fharms** [comment]
Thanks for reporting this. 

It's known limit with the plugin, and something we are working on in general to improve parsing of endpoint with variables, resolve property placeholders etc.

**Comment by davsclaus** [comment]
Are you using latest version of the plugin?

**Comment by close2infinity** [comment]
I am using the latest version, and I have the same problem. The possibility to define endpoints as fields (constant or not) is, in my eyes, a must-have for production code.

**Comment by davsclaus** [comment]
Just tried with latest code and this is still a problem

**Comment by mcollovati** [comment]
Did some experimental work on this; I've managed to get the icon shown for routes using variables or constants.
I tried it only with simple string variables.
If you want you can take a look this branch 

https://github.com/camel-idea-plugin/camel-idea-plugin/compare/master...mcollovati:camel-icon-for-non-string-uri?expand=1

![route-icon-1](https://cloud.githubusercontent.com/assets/4648894/25306284/406efd68-278a-11e7-9868-bb7e55bb57bd.png)

From the gutter you can navigate to the matching route or to the variable declaration

![route-icon-2](https://cloud.githubusercontent.com/assets/4648894/25306298/79aa7cec-278a-11e7-9a96-baa817078358.png)

![route-icon-3](https://cloud.githubusercontent.com/assets/4648894/25306299/815c6946-278a-11e7-9797-c503a49d11e6.png)

**Comment by davsclaus** [comment]
@mcollovati yay this looks good. 

This would be good to get fixed in the upcoming release. We are also waiting for Camel 2.19 to be released.

**Comment by mcollovati** [comment]
Added on the same branch also experimental support for start route expressions referencing methods

![route-icon-4](https://cloud.githubusercontent.com/assets/4648894/25355854/640606ae-2938-11e7-81ce-112496887233.png)

![icon-route-5](https://cloud.githubusercontent.com/assets/4648894/25355862/6c2dad5a-2938-11e7-9ee6-5cac34678701.png)

@davsclaus Are there any examples on how to write tests for non java language (kotlin, scala, groovy)?

**Comment by fharms** [comment]
@mcollovati at the moment we have no good way of testing the different languages. But we are working on it in #285

For now just create unit test for xml and java.

**Comment by davsclaus** [comment]
Yeah its hard to keep functionality on par for all languages and unit tests as well. I think we will focus primarily on java and xml. And then with #285 make the other languages more optional and maybe have a feature matrix where we mark [x] what each language can and cannot do.

Great work @mcollovati we should get this into the next release. We are also waiting a bit for Camel 2.19.0 to come out so we can upgrade and use a stable version onwards.

**Comment by davsclaus** [comment]
@mcollovati do you mind creating a PR with your work so we can get this in a new release. I would like to get a release out with the 2.19.0 Camel release

**Comment by mcollovati** [comment]
@davsclaus I've created the PR.
I did not had time to do good manual tests for languages not covered by unit test. 
I did only a simple check on camel-example-scala from camel repository and fixed some issues introduced by my changes.
Can you suggest me some public example projects in scala, kotlin and groovy on which I can do manual test?

**Comment by davsclaus** [comment]
I have use the examples from Apache Camel for those languages,

https://github.com/apache/camel/tree/master/examples

There is for scala, kotlin and groovy in there.

**Comment by davsclaus** [comment]
Thanks @mcollovati merged your PR

**Comment by davsclaus** [comment]
Okay we have the icon now, lets just close this ticket and new tickets can be opened if more work is need. The scala and groovy languages are not a priority. Its too much hazzle to maintain, and we need that stuff @fharms is looking into to have scala and groovy as psi optional integrations so we can leverage that api instead of how we do now which is kinda of a hack
