### ISSUE TITLE
Show Camel icon in gutter in rest-dsl

### ISSUE THREAD

**Issue by davsclaus** [camel-idea-plugin/camel-idea-plugin#314]
We should show Camel icon when using rest-dsl, where we have each rest operation, eg get/post etc.

**Comment by bennetelli** [comment]
rest("/say") 
    .get("/hello").to("direct:hello")
    .get("/bye").consumes("application/json").to("direct:bye")
    .post("/bye").to("mock:update");
from("direct:hello")
    .transform().constant("Hello World");
from("direct:bye")
    .transform().constant("Bye World");


@davsclaus You want to have camel Icons at rest(), from() and from() methods, right?

**Comment by davsclaus** [comment]
@bennetelli we already have in the `from` methods today, those are regular Camel routes.

We should have a Camel icon, on `rest()` and rest("xxx")` as well, eg to denote its Camel, eg Camel Rest DSL.

**Comment by davsclaus** [comment]
For a Java example see
https://github.com/apache/camel/blob/master/examples/camel-example-cdi-rest-servlet/src/main/java/org/apache/camel/example/cdi/rest/servlet/Application.java

And for XML
https://github.com/apache/camel/blob/master/examples/camel-example-servlet-rest-blueprint/src/main/resources/OSGI-INF/blueprint/camel.xml#L56

**Comment by davsclaus** [comment]
We can argue if we should have it for each operation, eg get/post etc but that can maybe be too much. Lets try for starters to do it only on the root rest element.

**Comment by bennetelli** [comment]
@davsclaus in my opinion it would be too much as well. So lets stay with "camel icons for rest() and rest("xxx) methods"

**Comment by bennetelli** [comment]
@davsclaus Should the camel icon next to rest() or rest("/say") just show there is a camel route start or do we need something else? "navigate to" or something like this? any additional features except the camel icon itself?

**Comment by davsclaus** [comment]
Yeah a Camel icon at rest() or rest("/xxx") is fine to start with. I cannot yet see any useable navigation at this point.
