### ISSUE TITLE
Plugin can't find the camel-core/camel-catalog version

### ISSUE THREAD

**Issue by jonjon1123** [camel-idea-plugin/camel-idea-plugin#317]
I have a project that is using the 2.17.0.REDHAT-630187 version of camel-core. We are proxying the Red Hat GA repo in our Nexus repo. I have added our Nexus repo to my settings.xml and get the warning `Camel IDEA plugin cannot download camel-catalog with version 2.17.0.REDHAT-630187. Will fallback and use version 2.19.2`. I also tried to add our Nexus repository directly to the projects POM, but I received the same error. For some reason, the plugin can't find this version of the camel-catalog/camel-core.

**Comment by davsclaus** [comment]
Are you using one of the latest versions of this plugin? In your pom.xml you should be able to add 3rd party maven repositories in the `<repositories>` section which the plugin then will use for downloading the JAR. You can also try to download it manually and install in your own local m2/repo on your computer, which the plugin look in first before trying to download

**Comment by jonjon1123** [comment]
I believe I am using the latest version (0.4.4). I tried both of your suggestions and neither seemed to work. I attached 2 screenshots that show my Maven config in IntelliJ and my local Maven repo. As you can see, IntelliJ is pointed to my local Maven repo and my local Maven repo has the camel-catalog version .jar for 2.17.0.REDHAT-630187. Any other thoughts or things I could try?
![maven_settings](https://user-images.githubusercontent.com/691969/31181169-41333ff6-a8e6-11e7-9ae1-ac110c783f5b.jpg)
![maven_repo](https://user-images.githubusercontent.com/691969/31181174-44326f2e-a8e6-11e7-915f-c998547e1321.jpg)

**Comment by davsclaus** [comment]
Try adding to the pom.xml file of your Camel project directly, a `<repository> section where you point to your nexus repository. 

The IDEA plugin is using camel-catalog-maven to downlaod the JAR, which uses Groovy Grape and Apache Ivy. So this guy may not respect/use whatever m2 settings.xml stuff you have etc.

We use this API to add 3rd party maven repo's
https://github.com/apache/camel/blob/master/platforms/camel-catalog-maven/src/main/java/org/apache/camel/catalog/maven/MavenVersionManager.java#L80

And those 3rd party maven repo's are discovered from the project pom.xml file
https://github.com/camel-idea-plugin/camel-idea-plugin/blob/master/camel-idea-plugin/src/main/java/org/apache/camel/idea/service/CamelService.java#L328

**Comment by jonjon1123** [comment]
I added the following to my Camel projects pom.xml and it still couldn't find the correct version.
```
         <repositories>
		<repository>
			<releases>
				<enabled>true</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
			<id>nexus-repo</id>
			<name>Nexus Repo</name>
			<url>http://brtuxdevop03p.phillips66.net:8081/nexus/content/groups/public</url>
			<layout>default</layout>
		</repository>
	</repositories>
```
I had a hunch that it may have something to do with the fact that it is a REDHAT-630187 version so I changed the camel-core version to 2.17.0 (no REDHAT-630187) and it worked as expected. So it seems the plugin doesn't like the REDHAT-630187 version for some reason.

**Comment by davsclaus** [comment]
Are you use redhat in lower-case, eg it must be exact as the version in those JARs as shown in your screenshot, eg `2.17.0.redhat-630187`

**Comment by jonjon1123** [comment]
Looks like the versions are in lowercase. Something must be converting it to uppercase prior to showing the warning message in IntelliJ.

**Comment by jonjon1123** [comment]
Looks like this line is where is it converted to uppercase: https://github.com/camel-idea-plugin/camel-idea-plugin/blob/426ff0b388560b281363a8f2a5fbff35ff37bcab/camel-idea-plugin/src/main/java/org/apache/camel/idea/service/CamelService.java#L194

If the version must be in lowercase to resolve properly, this looks like a bug.

**Comment by davsclaus** [comment]
@jonjon1123 ah thanks, indeed that is a bug. I vaguely recall something about IDEA expecting it to be in upper-case. But we can store the original version as-is as well, and use that for that maven downloader.

**Comment by davsclaus** [comment]
Okay got a fix for this now where it says

     19.49	Camel IDEA plugin is using camel-catalog version 2.17.0.redhat-630187

**Comment by davsclaus** [comment]
Fixed now, will be in the next plugin release which we are waiting for Camel 2.20.0 to be released first.

**Comment by jonjon1123** [comment]
Excellent! Thanks for your help!

**Comment by jonjon1123** [comment]
Excellent! Thanks for your help!
