### ISSUE TITLE
Can't run tests on console

### ISSUE THREAD

**Issue by bennetelli** [camel-idea-plugin/camel-idea-plugin#321]
Hi there,

Running the integration tests works fine when running in IntelliJ but it doesn't work via console. What do I have to do?

best,
Bennet

**Comment by bennetelli** [comment]
I always get a RuntimeException with this message:"Cannot load resource: /idea/IdeaApplicationInfo.xml" when running the tests on the command line

**Comment by fharms** [comment]
Not something I recall seeing before

Do you use the CE or Ultimate edition?

**Comment by bennetelli** [comment]
I'm using Ultimate

**Comment by fharms** [comment]
I was afraid of that. There has been some weird dependency issue each time we upgrade IDEA and typical it's because of missing dependencies. 

You will have to look through the output of your console and look for hints and properly debug. But it can be a tough one to track down. Otherwise you can switch to CE instead and it will build fine

**Comment by bennetelli** [comment]
Ok, will try to find a solution for it.

**Comment by fharms** [comment]
Maybe @davsclaus knows, if I remember correct he is also using the Ultimate

**Comment by davsclaus** [comment]
I dont get that error, I just run

    mvn clean install -P ultimate

And the project is in `/workspace/camel-idea-plugin` on my laptop

**Comment by davsclaus** [comment]
What version of Maven do you use? I use 3.5.0.

We can of course also use maven wrapper that some projects do so you run via mvnw which then download and use the same version always

**Comment by bennetelli** [comment]
pretty strange.. it's not a Maven issue. I'm using 3.5.0 as well. Removed and Downloaded all the stuff again and everything works fine. Will keep an eye on it. Let's close this issue for now.

**Comment by davsclaus** [comment]
Okay closing - more contributions is surely welcome
