### ISSUE TITLE
Should we add images to the readme page?

### ISSUE THREAD

**Issue by bennetelli** [camel-idea-plugin/camel-idea-plugin#330]
I just added an image to the readme page because I think it would be nice for beginners to see images instead of text to see what the plugin offers, but I don't know if you like it or not.

Should we describe the plugin features by text or should we also add images to the readme file?

**Comment by bennetelli** [comment]
sorry.. I added the image to the readme before asking one of you if it's okay and if you like it as plugin documentation.

**Comment by davsclaus** [comment]
Yeah that is fine, thanks. Feel free to improve the project as you like.

**Comment by bennetelli** [comment]
@fharms how did you create the animiated gif?

**Comment by fharms** [comment]
@bennetelli I'm using licecap from cockos. It's working both on Windows and OSX and currently using it on OSX

**Comment by bennetelli** [comment]
Thanks @fharms
