### ISSUE TITLE
Bug in Plugin Preferences Lists

### ISSUE THREAD

**Issue by bennetelli** [camel-idea-plugin/camel-idea-plugin#336]
![untitled](https://user-images.githubusercontent.com/8372856/31506204-141d611c-af77-11e7-99c1-f55a6113f84e.gif)

**Comment by bennetelli** [comment]
@davsclaus @fharms I spent at least 16 hours on fixing the apply bug.. 
When I add the tables to the page only (without the checkboxes above) everything works fine. Would it be an option to split this preferences page in two separate ones? (like it is in Schemas and DTDs or Stylesheets) Maybe this can fix the bug. What do you think of it?

**Comment by fharms** [comment]
I have been fighting with various strange problems when it comes to IDEA SDK so I'm not really surprised. 

You could also try their developer forum and ask for help, but feel free to try out your suggestion.

**Comment by davsclaus** [comment]
@bennetelli yeah sure you are welcome to change the preference to get it fixed. Maybe there can be tabbed panes so you select a pane for those properties. It may also make it less clutter as today there is many options on that single page.

**Comment by bennetelli** [comment]
what's a meaningful name for this category or preferences?

<img width="988" alt="camel-preference-categories" src="https://user-images.githubusercontent.com/8372856/31713311-2cd3d962-b3fe-11e7-8fa2-2510ce9b484e.png">

**Comment by fharms** [comment]
@bennetelli that's good question. what about just call it "settings" or "editor settings"

btw I tried to do the same test as you do in the first GIF, but can't reproduce the error.

**Comment by bennetelli** [comment]
strange.. if it's not reproducible, my "bugfix" will lead to less code anyway. Found a solution to replace the custom Tables and TableModels by plain Idea stuff :-)
