### ISSUE TITLE
Adjust Checkstyle configuration

### ISSUE THREAD

**Issue by bennetelli** [camel-idea-plugin/camel-idea-plugin#338]
The new checkstyle configuration isn't 100% compatible to the former version.
When formatting code in intelliJ the formatter groups imports and separates these groups from each other by blank new lines between them.
The new checkstyle configuration does not allow it. So we should change the checkstyle config to allow grouping of imports

**Comment by bennetelli** [comment]
@davsclaus it seems like the standard IntellIJ formatter settings  are not 100% compatible to the new and old version of our checkstyle configuration. Can you confirm it? We should take care when updating the checkstyle configuration of Apache Camel..

**Comment by davsclaus** [comment]
Ah okay, yeah maybe leave it as-is so its the same as Apache Camel. Its best they are similar.
