### ISSUE TITLE
Route navigator should support constants

### ISSUE THREAD

**Issue by NielsUll** [camel-idea-plugin/camel-idea-plugin#356]
We usually declare our direct endpoints as constants:
   
 ```
  public static final String DIRECT_RETURN_INVALID_STATE = "direct:returnInvalidState";
   ...

   from(DIRECT_RETURN_INVALID_STATE)
   ...


   ...
   .to(DIRECT_RETURN_INVALID_STATE)
```
Unfortunately, the route navigator will jump to the declaration of the constant, which is not very useful.
Could it be smarter when the from/to is a constant expression, using the PsiConstantEvaluationHelper.computeConstantExpression to get the actual constant?

**Comment by davsclaus** [comment]
You are welcome to dive into the source code and try to implement this

**Comment by davsclaus** [comment]
Trying to look into this today

**Comment by davsclaus** [comment]
Took a while for me to get back into IDEA Psi ... hell.

However it seems the constants jump to is working. 
<img width="546" alt="screen shot 2017-11-18 at 15 23 25" src="https://user-images.githubusercontent.com/477100/32981268-85902b8a-cc74-11e7-8301-ee48580d9059.png">

**Comment by NielsUll** [comment]
Thanks! I was looking into it, but got lost in Psi..
