### ISSUE TITLE
Add support for manual swiching version of Camel in the project

### ISSUE THREAD

**Issue by formatq** [camel-idea-plugin/camel-idea-plugin#365]
Please, add support for manual swiching version of Camel in the project if is it possible. For example add listbox in the Camel Plugin submenu in Settings.

**Comment by davsclaus** [comment]
Just change the camel version in the maven pom.xml file or whatever you do for managing your JAR dependencies. Then the plugin should detect this and load the version of Camel you are using.

**Comment by formatq** [comment]
Thanks, it's works
