### ISSUE TITLE
Use Jetbrains new Maven repository

### ISSUE THREAD

**Issue by fharms** [camel-idea-plugin/camel-idea-plugin#380]
Jetbrains has started to upload their SDK to a maven repository. They also created a gradle plugin to make it easy to build and distribute plug-ins

https://github.com/JetBrains/gradle-intellij-plugin

I'm unsure how much work it will take to make it work with the new maven structure because of the way we distinguish between EAP and CE version. But the real benefit will come if we convert our maven build to use gradle build instead

**Comment by bennetelli** [comment]
Just found this plugin: https://github.com/LendingClub/gradle-maven-plugin
Maybe we would use it to get the IDEA SDK dependencies.

Unfortunately I didn't find any repositories containing the jars of the SDK lib folder in the gradle plugin.

**Comment by bennetelli** [comment]
@davsclaus @fharms What about using Gradle instead of Maven? Is it an option? What do you think of it?

**Comment by fharms** [comment]
I'm fine with that. So whatever that make it easier to maintain IDEA dependencies and releases I vote for it

**Comment by bennetelli** [comment]
I think a switch to Gradle would improve the update process a lot and it also would decrease the turnaround times of implementing, building and manually testing a plugin snapshot version becuase the gradle plugin comes with some very helpful tasks to do this.

**Comment by davsclaus** [comment]
Yeah sure works for me too.
